---
- name: Install bind & related packages
  apt:
    name: "{{item}}"
    state: present
  become: true
  with_items:
    - bind9
    - bind9utils

- name: Install DNS config
  copy:
    src: "{{item}}"
    dest: /etc/bind/
  become: true
  with_items:
    - named.conf.options
    - named.conf.local
  notify:
    - restart bind

- name: Ensure zones subdirectory
  file:
    path: /etc/bind/zones
    state: directory
    owner: root
    group: bind
    mode: 02755
  become: true

- name: Install zone databases
  copy:
    src: "{{item}}"
    dest: /etc/bind/zones
  become: true
  with_items:
    - db.192.168.1
    - db.home.lan
  notify:
    - restart bind

- name: Ensure bind is running now and at boot
  service:
    name: bind9
    enabled: yes
    state: started
  become: true
